# Generated by Django 2.2.3 on 2019-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20190703_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ip',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
